; version.asm
;
; Auto-generated by ZXVersion.exe
; On 09 Feb 2020 at 09:42

BuildNo                 macro()
                        db "4"
mend

BuildNoValue            equ "4"
BuildNoWidth            equ 0 + FW4



BuildDate               macro()
                        db "09 Feb 2020"
mend

BuildDateValue          equ "09 Feb 2020"
BuildDateWidth          equ 0 + FW0 + FW9 + FWSpace + FWF + FWe + FWb + FWSpace + FW2 + FW0 + FW2 + FW0



BuildTime               macro()
                        db "09:42"
mend

BuildTimeValue          equ "09:42"
BuildTimeWidth          equ 0 + FW0 + FW9 + FWColon + FW4 + FW2



BuildTimeSecs           macro()
                        db "09:42:36"
mend

BuildTimeSecsValue      equ "09:42:36"
BuildTimeSecsWidth      equ 0 + FW0 + FW9 + FWColon + FW4 + FW2 + FWColon + FW3 + FW6
