; version.asm
;
; Auto-generated by ZXVersion.exe
; On 22 Jan 2020 at 15:48

BuildNo                 macro()
                        db "59"
mend

BuildNoValue            equ "59"
BuildNoWidth            equ 0 + FW5 + FW9



BuildDate               macro()
                        db "22 Jan 2020"
mend

BuildDateValue          equ "22 Jan 2020"
BuildDateWidth          equ 0 + FW2 + FW2 + FWSpace + FWJ + FWa + FWn + FWSpace + FW2 + FW0 + FW2 + FW0



BuildTime               macro()
                        db "15:48"
mend

BuildTimeValue          equ "15:48"
BuildTimeWidth          equ 0 + FW1 + FW5 + FWColon + FW4 + FW8



BuildTimeSecs           macro()
                        db "15:48:14"
mend

BuildTimeSecsValue      equ "15:48:14"
BuildTimeSecsWidth      equ 0 + FW1 + FW5 + FWColon + FW4 + FW8 + FWColon + FW1 + FW4
