#!/usr/bin/python
#
# WARNING -- THIS HAS NO ERROR CHECKING
#
import sys
import os
import argparse

parser = argparse.ArgumentParser(description='Read INT bytes of data from STDIN, rewrite it to STDOUT, then terminate.')
parser.add_argument('bytes', metavar='bytes', type=int,
                    help='Number of bytes to read')

args = parser.parse_args()

bytes_left = args.bytes

while bytes_left:
    byte  = os.read(0, 1)
    bytes_left = bytes_left - 1
    sys.stdout.write(byte)
