; version.asm
;
; Auto-generated by ZXVersion.exe
; On 16 Feb 2020 at 21:02

BuildNo                 macro()
                        db "69"
mend

BuildNoValue            equ "69"
BuildNoWidth            equ 0 + FW6 + FW9



BuildDate               macro()
                        db "16 Feb 2020"
mend

BuildDateValue          equ "16 Feb 2020"
BuildDateWidth          equ 0 + FW1 + FW6 + FWSpace + FWF + FWe + FWb + FWSpace + FW2 + FW0 + FW2 + FW0



BuildTime               macro()
                        db "21:02"
mend

BuildTimeValue          equ "21:02"
BuildTimeWidth          equ 0 + FW2 + FW1 + FWColon + FW0 + FW2



BuildTimeSecs           macro()
                        db "21:02:41"
mend

BuildTimeSecsValue      equ "21:02:41"
BuildTimeSecsWidth      equ 0 + FW2 + FW1 + FWColon + FW0 + FW2 + FWColon + FW4 + FW1
