; version.asm
;
; Auto-generated by ZXVersion.exe
; On 01 Feb 2020 at 19:57

BuildNo                 macro()
                        db "250"
mend

BuildNoValue            equ "250"
BuildNoWidth            equ 0 + FW2 + FW5 + FW0



BuildDate               macro()
                        db "01 Feb 2020"
mend

BuildDateValue          equ "01 Feb 2020"
BuildDateWidth          equ 0 + FW0 + FW1 + FWSpace + FWF + FWe + FWb + FWSpace + FW2 + FW0 + FW2 + FW0



BuildTime               macro()
                        db "19:57"
mend

BuildTimeValue          equ "19:57"
BuildTimeWidth          equ 0 + FW1 + FW9 + FWColon + FW5 + FW7



BuildTimeSecs           macro()
                        db "19:57:14"
mend

BuildTimeSecsValue      equ "19:57:14"
BuildTimeSecsWidth      equ 0 + FW1 + FW9 + FWColon + FW5 + FW7 + FWColon + FW1 + FW4
